theme: NoCommandBar
backgroundTranslucentEffect: ''
backgroundTranslucentEffectRegion: ''
controlStyles:
  - target: ''
    styles:
      - ''
styleConstants:
  - ''
themeResourceVariables:
  - ''
explorerFrameContainerHeight: 0
xamlDiagnosticsHandling: alert
resourceVariables:
  - variableKey: ''
    value: ''
