theme: ''
controlStyles:
  - target: Grid#NotificationCenterGrid
    styles:
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
      - VerticalAlignment=Stretch
      - CornerRadius=$r
  - target: Grid#CalendarCenterGrid
    styles:
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
      - CornerRadius=$r
  - target: Grid#ControlCenterRegion
    styles:
      - Margin=$screenfix
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
      - CornerRadius=$r
  - target: Grid#MediaTransportControlsRegion
    styles:
      - Margin=$screenfix2
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
      - CornerRadius=$r
  - target: ControlCenter.FrameWithContentChanged#L2Frame
    styles:
      - Padding=0,0,0,11
  - target: Border#ToastBackgroundBorder2
    styles:
      - CornerRadius=$r
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush=$border
  - target: MenuFlyoutPresenter
    styles:
      - CornerRadius=$r
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
  - target: Border#JumpListRestyledAcrylic
    styles:
      - CornerRadius=$r
      - Background:=$bg
      - BorderThickness=1
      - Shadow:=
      - BorderBrush:=$border
  - target: ActionCenter.FlexibleToastView#FlexibleNormalToastView
    styles:
      - Background:=Transparent
      - Shadow:=
  - target: ActionCenter.FlexibleItemView
    styles:
      - Shadow:=
  - target: ScrollViewer#CalendarControlScrollViewer
    styles:
      - Background:=Transparent
      - BorderThickness=0
  - target: ScrollViewer#ListContent
    styles:
      - CornerRadius=$r
      - Background:=Transparent
      - Shadow:=
  - target: ContentPresenter#PageContent
    styles:
      - Background:=Transparent
      - Shadow:=
  - target: ContentPresenter#PageContent > Grid > Border
    styles:
      - Background:=Transparent
      - Shadow:=
  - target: QuickActions.ControlCenter.AccessibleWindow#PageWindow > ContentPresenter > Grid#FullScreenPageRoot
    styles:
      - Background:=Transparent
      - Shadow:=
  - target: QuickActions.ControlCenter.AccessibleWindow#PageWindow > ContentPresenter > Grid#FullScreenPageRoot > ContentPresenter#PageHeader
    styles:
      - Background:=Transparent
      - Shadow:=
  - target: Grid#NotificationCenterTopBanner
    styles:
      - Background:=Transparent
  - target: Grid#L1Grid > Border
    styles:
      - CornerRadius=$r
      - Background:=Transparent
  - target: Windows.UI.Xaml.Controls.Image#IconImage
    styles:
      - Visibility=Collapsed
  - target: TextBlock#AppNameText
    styles:
      - Margin=160,0,0,-40
  - target: StackPanel#PrimaryAndSecondaryTextContainer
    styles:
      - Margin=160,-10,0,0
  - target: Grid#ThumbnailImage
    styles:
      - Grid.Column=0
      - Margin=-5,-10,0,0
      - Height=140
      - Width=140
      - CornerRadius=$r
  - target: ListView#MediaButtonsListView
    styles:
      - RenderTransform:=<ScaleTransform ScaleX="0.9" ScaleY="0.9" />
      - RenderTransformOrigin=0.5,0.5
      - Margin=0,-30,0,0
      - HorizontalAlignment=2
  - target: Grid#MediaTransportControlsRoot
    styles:
      - Background:=Transparent
  - target: Windows.UI.Xaml.Controls.Grid#FooterGrid
    styles:
      - BorderThickness=0
  - target: ContentPresenter > Windows.UI.Xaml.Controls.Border
    styles:
      - BorderThickness=0
  - target: ActionCenter.FocusSessionControl
    styles:
      - Height=0
  - target: Windows.UI.Xaml.Controls.Button#SessionSwitchButton
    styles:
      - Margin=0,0,-10,-40
  - target: ControlCenter.PaginatedToggleButton#ToggleButton > ContentPresenter#ContentPresenter
    styles:
      - BorderThickness=1
      - BorderBrush:=$border
  - target: ControlCenter.PaginatedToggleButton#SplitL2Button > ContentPresenter#ContentPresenter
    styles:
      - BorderThickness=1,0,0,0
      - BorderBrush:=$border
  - target: Windows.UI.Xaml.Controls.ContentControl#TogglesGroup > Windows.UI.Xaml.Controls.ContentPresenter > ControlCenter.PaginatedGridView > Windows.UI.Xaml.Controls.Grid
    styles:
      - CornerRadius=$r
      - BorderThickness=0
  - target: Windows.UI.Xaml.Controls.ScrollViewer#PipsPagerScrollViewer
    styles:
      - Visibility=Collapsed
  - target: Microsoft.UI.Xaml.Controls.ItemsRepeater > Windows.UI.Xaml.Controls.Button
    styles:
      - Visibility=Collapsed
  - target: ControlCenter.ControlCenterPage
    styles:
      - RenderTransform:=<RotateTransform Angle="180" />
      - RenderTransformOrigin=0.5,0.5
  - target: ControlCenter.ControlCenterPage > Grid#RootGrid
    styles:
      - RenderTransform:=<RotateTransform Angle="180" />
      - RenderTransformOrigin=0.5,0.5
  - target: Windows.UI.Xaml.Shapes.Rectangle#HorizontalTrackRect
    styles:
      - Margin=0,-10,10,-10
      - Opacity=0.3
  - target: Windows.UI.Xaml.Shapes.Rectangle#HorizontalDecreaseRect
    styles:
      - Margin=0,-10,-10,-10
      - Height=4
  - target: Windows.UI.Xaml.Controls.Primitives.Thumb#HorizontalThumb
    styles:
      - Visibility=Visible
      - Height=20
      - Width=20
      - Margin=0
  - target: Windows.UI.Xaml.Controls.Primitives.Thumb#HorizontalThumb > Windows.UI.Xaml.Controls.Border
    styles:
      - Background:=<WindhawkBlur BlurAmount="5" TintColor="#00FFFFFF"/>
      - BorderBrush:=<SolidColorBrush Color="White" Opacity="0.2"/>
      - BorderThickness=1
      - CornerRadius=15
  - target: Windows.UI.Xaml.Controls.Primitives.Thumb#HorizontalThumb > Windows.UI.Xaml.Controls.Border > Windows.UI.Xaml.Shapes.Ellipse#SliderInnerThumb
    styles:
      - Visibility=Visible
  - target: Windows.UI.Xaml.Controls.Primitives.ScrollBar#VerticalScrollBar
    styles:
      - Visibility=1
  - target: Grid#SuggestionUIGrid
    styles:
      - Background:=$bg
      - CornerRadius=$r
  - target: Windows.UI.Xaml.Controls.Border#ItemOpaquePlating
    styles:
      - BorderThickness=1
      - BorderBrush:=$border
      - Background:=Transparent
      - CornerRadius=$r
  - target: Windows.UI.Xaml.Controls.ToolTip > Windows.UI.Xaml.Controls.ContentPresenter#LayoutRoot
    styles:
      - Background:=$bg2
      - BorderBrush:=$border
      - BorderThickness=1
  - target: Windows.UI.Xaml.Controls.ToolTip > Windows.UI.Xaml.Controls.ContentPresenter
    styles:
      - BorderThickness=1
      - BorderBrush:=$border
      - CornerRadius=$r
      - Shadow:=
styleConstants:
  - bg=<WindhawkBlur BlurAmount="20" TintColor="{ThemeResource SystemChromeLowColor}" TintOpacity="0.6" />
  - bg2=<WindhawkBlur BlurAmount="10" TintColor="{ThemeResource SystemChromeLowColor}" TintOpacity="0.3" />
  - bgx=<WindhawkBlur BlurAmount="7" TintColor="{ThemeResource SystemChromeLowColor}" TintOpacity="0.5" />
  - border=<LinearGradientBrush StartPoint="0,0" EndPoint="0,1" Opacity="0.15"><GradientStop Color="{ThemeResource TextFillColorSecondary}" Offset="0.0"/><GradientStop Color="{ThemeResource TextFillColorTertiary}" Offset="0.5"/><GradientStop Color="{ThemeResource TextFillColorSecondary}" Offset="1.0"/></LinearGradientBrush>
  - r=10
  - screenfix=0,0,0,683
  - screenfix2=0,0,0,-875
resourceVariables:
  - variableKey: ''
    value: ''
